# Generated by Django 6.0.7 on 2026-07-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
                ('coursecode', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
