# Generated by Django 6.0.7 on 2026-07-19 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
