# Generated by Django 6.0.7 on 2026-07-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default=8888888888),
            preserve_default=False,
        ),
    ]
