# Generated by Django 6.0.7 on 2026-07-19 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
